// <auto-generated />
using System;
using BankTransfers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankTransfers.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200923102415_AlterCommisionMatrix")]
    partial class AlterCommisionMatrix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("BankTransfers.Data.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("BankId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "1",
                            Name = "Физическое лицо"
                        },
                        new
                        {
                            Id = 2,
                            Code = "2",
                            Name = "Юридическое лицо"
                        },
                        new
                        {
                            Id = 3,
                            Code = "3",
                            Name = "Нерезидент"
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BIC = "044525225",
                            Name = "Сбербанк"
                        },
                        new
                        {
                            Id = 2,
                            BIC = "044525187",
                            Name = "ВТБ"
                        },
                        new
                        {
                            Id = 3,
                            BIC = "044525593",
                            Name = "Альфабанк"
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.BankCommision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<int?>("BankTransferTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("BankTransferTypeId");

                    b.ToTable("BankCommisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 1,
                            BankTransferTypeId = 1,
                            Rate = 0m
                        },
                        new
                        {
                            Id = 2,
                            BankId = 1,
                            BankTransferTypeId = 2,
                            Rate = 1.0m
                        },
                        new
                        {
                            Id = 3,
                            BankId = 2,
                            BankTransferTypeId = 1,
                            Rate = 0m
                        },
                        new
                        {
                            Id = 4,
                            BankId = 2,
                            BankTransferTypeId = 2,
                            Rate = 2.0m
                        },
                        new
                        {
                            Id = 5,
                            BankId = 3,
                            BankTransferTypeId = 1,
                            Rate = 1.0m
                        },
                        new
                        {
                            Id = 6,
                            BankId = 3,
                            BankTransferTypeId = 2,
                            Rate = 2.5m
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.BankTransferType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankTransferTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Внутренний перевод"
                        },
                        new
                        {
                            Id = 2,
                            Name = "На счет в другом банке"
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Security.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@mail.ru",
                            Password = "Kfe2prNZ+q8hlGnS//VRXKNBYeJoYrwUTqlamCPhNog=",
                            RoleId = 1,
                            Salt = "SBTSFagheVpqel2XlSuErw=="
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BankCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecipientAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderAccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransferCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAccountId");

                    b.HasIndex("SenderAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.TransferCommision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RecipientAccountTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SenderAccountTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAccountTypeId");

                    b.HasIndex("SenderAccountTypeId");

                    b.ToTable("TransferCommisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rate = 0m,
                            RecipientAccountTypeId = 1,
                            SenderAccountTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Rate = 0m,
                            RecipientAccountTypeId = 2,
                            SenderAccountTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Rate = 0m,
                            RecipientAccountTypeId = 3,
                            SenderAccountTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Rate = 2.0m,
                            RecipientAccountTypeId = 1,
                            SenderAccountTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Rate = 3.0m,
                            RecipientAccountTypeId = 2,
                            SenderAccountTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Rate = 4.0m,
                            RecipientAccountTypeId = 3,
                            SenderAccountTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Rate = 4.0m,
                            RecipientAccountTypeId = 1,
                            SenderAccountTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Rate = 6.0m,
                            RecipientAccountTypeId = 2,
                            SenderAccountTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Rate = 6.0m,
                            RecipientAccountTypeId = 3,
                            SenderAccountTypeId = 3
                        });
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Account", b =>
                {
                    b.HasOne("BankTransfers.Data.Models.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId");

                    b.HasOne("BankTransfers.Data.Models.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankId");

                    b.Navigation("AccountType");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.BankCommision", b =>
                {
                    b.HasOne("BankTransfers.Data.Models.Bank", "Bank")
                        .WithMany("BankCommisions")
                        .HasForeignKey("BankId");

                    b.HasOne("BankTransfers.Data.Models.BankTransferType", "BankTransferType")
                        .WithMany()
                        .HasForeignKey("BankTransferTypeId");

                    b.Navigation("Bank");

                    b.Navigation("BankTransferType");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Security.User", b =>
                {
                    b.HasOne("BankTransfers.Data.Models.Security.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Transaction", b =>
                {
                    b.HasOne("BankTransfers.Data.Models.Account", "RecipientAccount")
                        .WithMany()
                        .HasForeignKey("RecipientAccountId");

                    b.HasOne("BankTransfers.Data.Models.Account", "SenderAccount")
                        .WithMany()
                        .HasForeignKey("SenderAccountId");

                    b.HasOne("BankTransfers.Data.Models.Security.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("RecipientAccount");

                    b.Navigation("SenderAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.TransferCommision", b =>
                {
                    b.HasOne("BankTransfers.Data.Models.AccountType", "RecipientAccountType")
                        .WithMany()
                        .HasForeignKey("RecipientAccountTypeId");

                    b.HasOne("BankTransfers.Data.Models.AccountType", "SenderAccountType")
                        .WithMany()
                        .HasForeignKey("SenderAccountTypeId");

                    b.Navigation("RecipientAccountType");

                    b.Navigation("SenderAccountType");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Bank", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BankCommisions");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Security.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BankTransfers.Data.Models.Security.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
